[cogs]

[cogs.admin]
enabled = true

[cogs.backloggd]
enabled = true
update_interval = 5
channels = [710120383235227670]

[cogs.chatbot]
enabled = true
token_window_size = 4096
max_images_in_window = 2
max_output_tokens = 1024
model_temperature = 0.9
model_top_p = 0.92
model_frequency_penalty = 0.1
model_presence_penalty = 0.1
default_model = "gpt-4.1-mini"
default_chat_prompt = "data/prompts/rosamund.yaml"
random_response_chance = 0.005
random_response_use_n_messages = 5
response_rate_limit = 3
rate_limit_interval = 5
enable_profiling = false
prefer_image_urls = false

[cogs.letterboxd]
enabled = true
update_interval = 5
channels = [237647756049514498, 710120383235227670]

[cogs.markov]
enabled = true

[cogs.reminders]
enabled = true

[cogs.scheduled_posts]
enabled = true

[cogs.spam]
enabled = true

[cogs.spelling]
enabled = true
custom_dictionary = "data/slash_dict.txt"

[cogs.spelling.servers."710120382144839691"]
users = [357550184655224833, 151378138612367360, 284782689226063874]
post_channel = 710120383235227670

[cogs.tools]
enabled = true

[cogs.users]
enabled = true

[cogs.videos]
enabled = true

[cogs.weather]
enabled = true

[cooldown]
rate = 3
standard = 60
no_cooldown_users = [151378138612367360]
no_cooldown_servers = [237647756049514498]

[discord]
max_chars = 1950
development_servers = [815237689775357992]

[files]
database = "data/slashbot.sqlite.db"
bad_words = "data/text/badwords.txt"
god_words = "data/text/godwords.txt"
scheduled_posts = "data/scheduled_posts.yaml"

[logging]
log_location = "logs/slashbot.log"

[markov]
enable_markov_training = false
enable_pregen_sentences = true
num_pregen_sentences = 5
pregenerate_limit = 2
